import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class UserSignUp extends javax.swing.JFrame {

    JFileChooser jfc=new JFileChooser();
    File obj_file;
    public UserSignUp() {
        initComponents();
        setSize(700,600);
        setVisible(true);
        setTitle("Sign Up Page");
        setLocation(400,400);
        getContentPane().setBackground(new Color(218,247,166));
        j_sec_que.removeAllItems();
        for(int i=0;i<GlobalClass.sec_que.length;i++)
        {
            j_sec_que.addItem(GlobalClass.sec_que[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jemail = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jconpass = new javax.swing.JPasswordField();
        j_sec_que = new javax.swing.JComboBox<>();
        j_secans = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Security Question");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Security Answer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 110, 16);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 390, 120, 50);
        getContentPane().add(jemail);
        jemail.setBounds(150, 60, 340, 40);
        getContentPane().add(jpass);
        jpass.setBounds(150, 110, 340, 40);
        getContentPane().add(jconpass);
        jconpass.setBounds(150, 160, 340, 40);

        j_sec_que.setBackground(new java.awt.Color(153, 255, 255));
        j_sec_que.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        j_sec_que.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(j_sec_que);
        j_sec_que.setBounds(150, 260, 340, 40);
        getContentPane().add(j_secans);
        j_secans.setBounds(150, 320, 340, 40);
        getContentPane().add(jphone);
        jphone.setBounds(150, 210, 340, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Mobile Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 220, 100, 20);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("<-Back to Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
        String email=jemail.getText();
        String password=jpass.getText();
        String confirmpassword=jconpass.getText();
        String mobileno=jphone.getText();
        String sec_ques=j_sec_que.getSelectedItem().toString();
        String sec_ans=j_secans.getText();
        if(email.isEmpty()|| password.isEmpty()||confirmpassword.isEmpty()||mobileno.isEmpty()||sec_ans.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"All Fields are mandatory");
        }
        else if(password.equals(confirmpassword))
        {
            try {
                ResultSet rs=DBLoader.executeQuery("Select * from admin where email='"+email+"' and password='"+password+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"User Already Exists");
                }
                else{
                    rs.moveToInsertRow();
                    rs.updateString("email",email);
                    rs.updateString("password",password);
                    rs.updateString("mobileno", mobileno);
                    rs.updateString("sec_ques", sec_ques);
                    rs.updateString("sec_ans", sec_ans);
                    rs.insertRow();
                    JOptionPane.showMessageDialog(this,"SignUp Successful");
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Password and Confirm Password does not match");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UserLogin obj=new UserLogin();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> j_sec_que;
    private javax.swing.JTextField j_secans;
    private javax.swing.JPasswordField jconpass;
    private javax.swing.JTextField jemail;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField jphone;
    // End of variables declaration//GEN-END:variables
}
